[tools]
rust = "1.94.0"

[tasks.update-recipes]
description = "Fetch FXW recipes from online and rebuild the recipes.json file"
run = "scripts/build_recipes"

[tasks.test]
description = "Run all tests"
run = "cargo test"

[tasks.build]
description = "Build a release version of the CLI. Use cargo run for dev"
run = "cargo build --release"

[tasks.install]
depends = ["update-recipes", "build", "test"]
description = "Install the CLI to $HOME/bin/fxraw"
run = "cp ./target/release/fxraw $HOME/bin/fxraw"
